name: 'Mazoea default start action'
description: 'Common tasks after job start'
inputs:
  MS_TEAMS_URI:
    description: 'webhook url'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: inputs
      run: |
        echo "${{ inputs.UID }}"
        echo "${{ inputs.GID }}"
        echo "${{ env.BRANCH }}"

    - name: services
      run: |
        git --version || true
        echo "=========================="

    - uses: mazoea/ga-maz/ms-teams-info@master
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ inputs.MS_TEAMS_URI }}
        notification-summary: 'Started [${{ github.repository }}] [${{ env.JOBNAME }}] by [${{ github.actor }}] on [${{ runner.os }}]'
        notification-color: '17a2b8'
      if: ${{ always() && inputs.MS_TEAMS_URI != '' }}
