name: 'Mazoea default end action'
description: 'Common tasks after job end'
inputs:
  MSG:
    description: 'message'
    required: false
    default: ''
  MS_TEAMS_URI:
    description: 'webhook url'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: inputs
      run: |
        echo "${{ inputs.UID }}"
        echo "${{ inputs.GID }}"
        echo "${{ inputs.MSG }}"
        echo "${{ env.BRANCH }}"

    - name: services
      run: |
        git --version || true
        echo "=========================="

    - name: detailed info
      run: |
        echo "${{ inputs.MSG }}"
      if: ${{ inputs.MSG != '' }}

    - uses: mazoea/ga-maz/ms-teams-info@master
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ inputs.MS_TEAMS_URI }}
        notification-color: '28a745'
        notification-summary: '&#x2705 Finished [${{ github.repository }}] [${{ env.JOBNAME }}] by [${{ github.actor }}] on [${{ runner.os }}]'
        notification-failure: '&#x1F621&#x1F621&#x1F621 FAILED [${{ github.repository }}] [${{ env.JOBNAME }}]'
        text: "${{ inputs.MSG }}"
        success: ${{ job.status == 'success' }}
      if: ${{ always() && inputs.MS_TEAMS_URI != '' }}
