name: 'Mazoea default end action'
description: 'Common tasks after job end'
inputs:
  CHOWN_DIR:
    description: 'change owner of directory'
    default: ''
    required: false
  UID:
    description: 'uid'
    default: '0'
    required: false
  GID:
    description: 'gid'
    default: '0'
    required: false
  MSG:
    description: 'message'
    required: false
    default: ''
  MS_TEAMS_URI:
    description: 'webhook url'
    required: false
    default: ''
runs:
  using: "composite"
  steps:

# linux

    - name: inputs
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "${{ inputs.UID }}"
        echo "${{ inputs.GID }}"
        echo "${{ inputs.MSG }}"
        echo "${{ env.BRANCH }}"

    - name: basic info
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        pwd || true
        echo "=========================="
        echo `hostname` || true
        echo "=========================="
        cat /opt/info/hostname || true
        echo "=========================="
        id || true
        echo "=========================="
        env || true
        echo "=========================="
        ls -lah || true
        echo "=========================="
        df -h | grep /$ || true
        echo "=========================="

    - name: services
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        git --version || true
        echo "=========================="

    - name: cleanup - change owner
      if: ${{ runner.os == 'Linux' && inputs.UID != '0' }}
      shell: bash
      run: |
        echo chown -R  ${{ inputs.UID }}:${{ inputs.GID }} ./
        chown -R  ${{ inputs.UID }}:${{ inputs.GID }} ./ || true

    - name: cleanup - change owner to default
      if: ${{ runner.os == 'Linux' && inputs.CHOWN_DIR != '' }}
      shell: bash
      run: |
        UUID=$(id -u)
        GGID=$(id -g)
        echo chown -R $UUID:$GGID ${{ inputs.CHOWN_DIR }}
        docker run --rm -v $(pwd):/app -w /app alpine chown -R $UUID:$GGID ${{ inputs.CHOWN_DIR }} || true

    - name: cleanup - docker
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "Docker repos login so we need to logout otherwise tokens stay and cause problems for next runs"
        docker logout ghcr.io || true

    - name: detailed info
      if: ${{ runner.os == 'Linux' && inputs.MSG != '' }}
      shell: bash
      run: |
        echo "${{ inputs.MSG }}"

# windows

    - name: inputs
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        echo "${{ inputs.UID }}"
        echo "${{ inputs.GID }}"
        echo "${{ inputs.MSG }}"
        echo "${{ env.BRANCH }}"

    - name: services
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        git --version || true
        echo "=========================="

    - name: detailed info
      if: ${{ runner.os == 'Windows' && inputs.MSG != '' }}
      shell: cmd
      run: |
        echo "${{ inputs.MSG }}"
