name: 'Mazoea default end action'
description: 'Common tasks after job end'
inputs:
  UID:
    description: 'uid'
    default: '0'
    required: false
  GID:
    description: 'gid'
    default: '0'
    required: false
  MSG:
    description: 'message'
    required: false
    default: ''
  MS_TEAMS_URI:
    description: 'webhook url'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: inputs
      shell: bash
      run: |
        echo "${{ inputs.UID }}"
        echo "${{ inputs.GID }}"
        echo "${{ inputs.MSG }}"
        echo "${{ env.BRANCH }}"

    - name: basic info
      shell: bash
      run: |
        pwd || true
        echo "=========================="
        echo `hostname` || true
        echo "=========================="
        cat /opt/info/hostname || true
        echo "=========================="
        id || true
        echo "=========================="

    - name: env
      shell: bash
      run: |
        env || true
        echo "=========================="

    - name: ls
      shell: bash
      run: |
        ls -lah || true
        echo "=========================="

    - name: services
      shell: bash
      run: |
        git --version || true
        echo "=========================="

    - name: disk
      shell: bash
      run: |
        df -h | grep /$ || true
        echo "=========================="

    - name: cleanup - change owner
      shell: bash
      run: |
        echo chown -R  ${{ inputs.UID }}:${{ inputs.GID }} ./
        chown -R  ${{ inputs.UID }}:${{ inputs.GID }} ./ || true
      if: ${{ inputs.UID != '0' }}

    - name: detailed info
      shell: bash
      run: |
        echo "${{ inputs.MSG }}"
      if: ${{ inputs.MSG != '' }}

    - uses: mazoea/ga-maz/ms-teams-info@master
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ inputs.MS_TEAMS_URI }}
        notification-color: '28a745'
        notification-summary: '&#x2705 Finished [${{ github.repository }}] [${{ env.JOBNAME }}] by [${{ github.actor }}] on [${{ runner.os }}]'
        notification-failure: '&#x1F621&#x1F621&#x1F621 FAILED [${{ github.repository }}] [${{ env.JOBNAME }}]'
        text: "${{ inputs.MSG }}"
        success: ${{ job.status == 'success' }}
      if: ${{ always() && inputs.MS_TEAMS_URI != '' }}
