name: 'Mazoea default start action'
description: 'Common tasks after job start'
inputs:
  UID:
    description: 'uid'
    default: '0'
    required: false
  GID:
    description: 'gid'
    default: '0'
    required: false
  MS_TEAMS_URI:
    description: 'webhook url'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: inputs
      shell: bash
      run: |
        echo "${{ inputs.UID }}"
        echo "${{ inputs.GID }}"
        echo "${{ env.BRANCH }}"

    - name: basic info
      shell: bash
      run: |
        pwd
        echo "=========================="
        echo `hostname`
        echo "=========================="
        cat /opt/info/hostname || true
        echo "=========================="
        id
        echo "=========================="

    - name: env
      shell: bash
      run: |
        env
        echo "=========================="

    - name: ls
      shell: bash
      run: |
        ls -lah
        echo "=========================="

    - name: services
      shell: bash
      run: |
        git --version || true
        echo "=========================="

    - name: disk
      shell: bash
      run: |
        df -h | grep /$ || true
        echo "=========================="

    - name: cleanup - change owner
      shell: bash
      run: |
        docker run --rm -e MAZUID=${{ inputs.UID }} -e MAZGID=${{ inputs.GID }} -v $(pwd):/maz registry.gitlab.com/mazoea-team/docker-ci-build:u18g8py38 /bin/bash -c 'ls -lah /maz && echo chown -R $MAZUID:$MAZGID /maz && (chown -R $MAZUID:$MAZGID /maz | tail -25) && ls -lah /maz' || true
      if: ${{ inputs.UID != '0' }}

    - uses: mazoea/ga-maz/ms-teams-info@master
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ inputs.MS_TEAMS_URI }}
        notification-summary: 'Started [${{ github.repository }}] [${{ env.JOBNAME }}] by [${{ github.actor }}] on [${{ runner.os }}]'
        notification-color: '17a2b8'
      if: ${{ always() && inputs.MS_TEAMS_URI != '' }}
