name: 'Mazoea default start action'
description: 'Common tasks after job start'
inputs:
  UID:
    description: 'uid'
    default: '0'
    required: false
  GID:
    description: 'gid'
    default: '0'
    required: false
  MS_TEAMS_URI:
    description: 'webhook url'
    required: false
    default: ''
runs:
  using: "composite"
  steps:

# linux

    - name: inputs
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "${{ inputs.UID }}"
        echo "${{ inputs.GID }}"
        echo "${{ env.BRANCH }}"

    - name: basic info
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        pwd || true
        echo "=========================="
        echo `hostname` || true
        echo "=========================="
        cat /opt/info/hostname || true
        echo "=========================="
        id || true
        echo "=========================="
        env || true
        echo "=========================="
        ls -lah || true
        echo "=========================="
        df -h | grep /$ || true
        echo "=========================="
        cat /proc/cpuinfo || true
        echo "=========================="

    - name: services
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: |
        echo "==== 2024.12 fixing GA/git checkout issues"
        git config http.version HTTP/1.1 || true
        echo "=========================="
        git --version || true
        echo "=========================="
        git config --list --show-origin
        echo "=========================="

    - name: cleanup - change owner
      if: ${{ runner.os == 'Linux' && inputs.UID != '0' }}
      shell: bash
      run: |
        docker run --rm -e MAZUID=${{ inputs.UID }} -e MAZGID=${{ inputs.GID }} -v $(pwd):/maz alpine:3.19.1 /bin/sh -c 'ls -lah /maz && echo chown -R $MAZUID:$MAZGID /maz && (chown -R $MAZUID:$MAZGID /maz | tail -25) && ls -lah /maz' || true

# windows

    - name: inputs
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        echo "${{ inputs.UID }}"
        echo "${{ inputs.GID }}"
        echo "${{ inputs.MSG }}"
        echo "${{ env.BRANCH }}"

    - name: detailed info
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        echo "=========================="
        ipconfig || true
        echo "=========================="

    - name: services
      if: ${{ runner.os == 'Windows' }}
      shell: cmd
      run: |
        echo "==== 2024.12 fixing GA/git checkout issues"
        git config http.version HTTP/1.1
        echo "=========================="
        set
        echo "=========================="
        git --version || true
        echo "=========================="
        git config --list --show-origin
        echo "=========================="

    - name: detailed info
      if: ${{ runner.os == 'Windows' && inputs.MSG != '' }}
      shell: cmd
      run: |
        echo "${{ inputs.MSG }}"
