name: Test
on:
  push:

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: ./start
      with:
        CONTEXT_GITHUB: ${{ toJson(github) }}
